### ISSUE TITLE
Multiple definition of library after updating

### ISSUE THREAD

**Issue by jdkadel** [mobizt/ESP32-Mail-Client#19]
Hey,
I'm using the ESP32-Mail-Client library with the Arduino 1.8.9 IDE / WEMOS LOLIN32 Lite board and when I upgraded from version 1.1.6 to 1.2.0 I started getting an error during compiling stating that there is a reuse of the HTTPClientESP32Ex library.

The best line I can see in the error log is 
c:\...\arduinodata\packages\esp32\tools\xtensa-esp32-elf-gcc\1.22.0-80-g6c4433a-5.2.0\xtensa-esp32-elf\include\c++\5.2.0\bits/unique_ptr.h:236: multiple definition of `HTTPClientESP32Ex::HTTPClientESP32Ex()'

I've uploaded the
[Multiple Libarary.txt](https://github.com/mobizt/ESP32-Mail-Client/files/3494120/Multiple.Libarary.txt)
 error log for additional information.

Any suggestions?

...Dave

**Comment by mobizt** [comment]
Please delete the HTTPClientESP32Ex library that you installed from libraries folder. This library is already added to ESP32 Mail Client library since latest version.
 Sorry for this inconvenience.

**Comment by jdkadel** [comment]
Complied fine. Thanks the the info and the library.

...Dave
